### PR TITLE
Added favicon to returned data

### PR DESCRIPTION
**Pull request by joshfarrant**
Adds favicon to returned data (if it exists) as discussed in #4.

Let me know if you're happy with the way that the favicon has been included in the responses @e-oj.

All tests are passing 👍

### CODE REVIEW

**Comment by e-oj** [comment]
Looks good to me. Solid work. Thanks for the pr.

**Comment by joshfarrant** [comment]
Great, thanks for merging 👌 

Any chance you could publish the new version to npm, if you haven't already? I'm hope to start using it right away!

**Comment by joshfarrant** [comment]
Whoops, I just realised that I didn't update the documentation in the README, sorry about that.

Would you like me to add the favicon in, or are you happy doing that?

**Comment by e-oj** [comment]
I was going to update the documentation and publish it. But feel free to carry out the update. I'll publish after that's merged

**Pull request merged**
